<?php

namespace yii\easyii\modules\rbac;

use Yii;

/**
 * GUI manager for RBAC.
 *
 * @property string $mainLayout Main layout using for module. Default to layout of parent module.
 * Its used when `layout` set to 'left-menu', 'right-menu' or 'top-menu'.
 * @property array $menus List available menu of module.
 * It generated by module items .
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class Module extends \yii\easyii\components\Module
{
    public function init()
    {
        parent::init();

        
    }
}
